# Generated by Django 6.1.2 on 2026-10-09 10:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('slug', models.SlugField(db_index=False, max_length=140, verbose_name='adresse')),
                ('category', models.CharField(choices=[('children', 'Enfants'), ('meals', 'Repas'), ('markets', 'Marchés'), ('games', 'Jeux'), ('festivities', 'Fêtes')], max_length=20, verbose_name='catégorie')),
                ('starts_at', models.DateTimeField(verbose_name='début')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('start_label', models.CharField(blank=True, help_text='Par exemple « Ouverture ».', max_length=40, verbose_name='libellé du début')),
                ('venue_name', models.CharField(max_length=120, verbose_name='lieu')),
                ('venue_address', models.CharField(blank=True, max_length=200, verbose_name='adresse du lieu')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('price_label', models.CharField(blank=True, max_length=60, verbose_name='tarif')),
                ('price_detail', models.CharField(blank=True, max_length=200, verbose_name='précision sur le tarif')),
                ('summary', models.TextField(blank=True, verbose_name='chapeau')),
                ('published', models.BooleanField(default=False, verbose_name='publié')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('lead', models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un membre du bureau.'}, limit_choices_to=models.Q(('is_active', True), models.Q(('is_superuser', True), ('groups__name', 'Bureau'), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_events', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('previous_edition', models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un événement existant.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_editions', to='events.event', verbose_name='édition précédente')),
            ],
            options={
                'verbose_name': 'événement',
            },
        ),
        migrations.CreateModel(
            name='PracticalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('people', 'Personnes'), ('home', 'Maison'), ('check', 'Coche'), ('info', 'Information'), ('warning', 'Attention'), ('parking', 'Stationnement'), ('food', 'Restauration'), ('accessibility', 'Accessibilité')], max_length=20, verbose_name='icône')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('text', models.TextField(blank=True, verbose_name='texte')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='ordre d’affichage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_infos', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': '« Bon à savoir »',
                'verbose_name_plural': '« Bon à savoir »',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='heure')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='ordre d’affichage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'ligne de programme',
                'verbose_name_plural': 'lignes de programme',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('slug',), name='event_unique_slug', violation_error_code='unique', violation_error_message='Un autre événement utilise déjà cette adresse.'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='event_ends_after_it_starts', violation_error_message='La fin de l’événement ne peut pas précéder son début.'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='event_complete_coordinates', violation_error_message='Indiquez la latitude et la longitude, ou aucune des deux.'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('previous_edition', models.F('pk')), _negated=True), name='event_not_its_own_previous_edition', violation_error_message='Un événement ne peut pas être sa propre édition précédente.'),
        ),
    ]
