# Generated by Django 6.1.2 on 2026-10-10 15:41

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanNumberSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='année')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='dernier numéro')),
            ],
            options={
                'verbose_name': 'compteur des numéros de prêt',
                'verbose_name_plural': 'compteurs des numéros de prêt',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('category', models.CharField(choices=[('furniture', 'Mobilier'), ('marquees', 'Barnums'), ('sound_and_light', 'Son et lumière'), ('kitchen', 'Cuisine'), ('street_and_games', 'Voirie et jeux')], max_length=20, verbose_name='catégorie')),
                ('storage_location', models.CharField(blank=True, max_length=120, verbose_name='rangement')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='quantité totale')),
                ('repair_quantity', models.PositiveIntegerField(default=0, verbose_name='en réparation')),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='valeur de remplacement')),
                ('repair_note', models.TextField(blank=True, verbose_name='note de réparation')),
            ],
            options={
                'verbose_name': 'matériel',
                'verbose_name_plural': 'matériels',
                'ordering': ['name', 'pk'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='equipment_unique_name', violation_error_message='Un matériel porte déjà ce nom.'), models.CheckConstraint(condition=models.Q(('repair_quantity__lte', models.F('total_quantity'))), name='equipment_repair_within_total', violation_error_message='La quantité en réparation dépasse la quantité totale.')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='numéro')),
                ('borrower_type', models.CharField(choices=[('association', 'Association'), ('individual', 'Particulier'), ('municipality', 'Commune'), ('committee', 'Usage comité')], max_length=20, verbose_name='type d’emprunteur')),
                ('borrower_name', models.CharField(blank=True, max_length=200, verbose_name='emprunteur')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='objet')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('start_date', models.DateField(verbose_name='sortie')),
                ('end_date', models.DateField(verbose_name='retour')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('out', 'Sorti'), ('returned', 'Rendu'), ('cancelled', 'Annulé')], default='confirmed', max_length=20, verbose_name='statut')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='caution')),
                ('notes', models.TextField(blank=True, verbose_name='remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='saisi le')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='rendu le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='saisi par')),
                ('event', models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un événement existant.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'prêt',
                'ordering': ['-start_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LoanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('damaged_quantity', models.PositiveIntegerField(default=0, verbose_name='abîmées')),
                ('missing_quantity', models.PositiveIntegerField(default=0, verbose_name='manquantes')),
                ('equipment', models.ForeignKey(error_messages={'invalid': 'Choisissez un matériel existant.'}, on_delete=django.db.models.deletion.PROTECT, related_name='loan_lines', to='equipment.equipment', verbose_name='matériel')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='equipment.loan', verbose_name='prêt')),
            ],
            options={
                'verbose_name': 'ligne de prêt',
                'verbose_name_plural': 'lignes de prêt',
                'ordering': ['equipment__name', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='loan_ends_after_start', violation_error_message='La date de retour est avant la date de sortie.'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('borrower_name', ''), ('borrower_type', 'committee'), ('deposit_amount', 0), ('event__isnull', False), ('number__isnull', True), ('phone', '')), models.Q(models.Q(('borrower_type', 'committee'), _negated=True), ('event__isnull', True), ('number__isnull', False), models.Q(('borrower_name', ''), _negated=True)), _connector='OR'), name='loan_committee_or_borrower', violation_error_message='Un usage comité réserve pour un événement, sans numéro, emprunteur, téléphone ni caution ; un prêt à un tiers a un numéro et un emprunteur.'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('returned_at__isnull', False), ('status', 'returned')), models.Q(models.Q(('status', 'returned'), _negated=True), ('returned_at__isnull', True)), _connector='OR'), name='loan_returned_when_dated', violation_error_message='Un prêt rendu porte la date de son retour.'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('event',), name='loan_unique_committee_event', violation_error_code='unique', violation_error_message='Cet événement a déjà sa réservation de matériel.'),
        ),
        migrations.AddConstraint(
            model_name='loanline',
            constraint=models.UniqueConstraint(fields=('loan', 'equipment'), name='loan_line_unique_equipment', violation_error_message='Ce matériel figure déjà dans le prêt.'),
        ),
        migrations.AddConstraint(
            model_name='loanline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='loan_line_some_pieces', violation_error_message='Indiquez au moins une pièce.'),
        ),
        migrations.AddConstraint(
            model_name='loanline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('damaged_quantity'), '+', models.F('missing_quantity')))), name='loan_line_return_within_quantity', violation_error_message='Les pièces abîmées et manquantes dépassent la quantité prêtée.'),
        ),
    ]
