# Generated by Django 6.1.2 on 2026-10-10 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_notification_group'),
        ('equipment', '0001_equipment_and_loans'),
        ('events', '0002_event_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document', verbose_name='convention signée'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('borrower_type', 'committee'), _negated=True), ('agreement__isnull', True), _connector='OR'), name='loan_committee_without_agreement', violation_error_message='Un usage comité n’a pas de convention.'),
        ),
    ]
