# Generated by Django 6.1.2 on 2026-10-10 11:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='saisie le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'réservation',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='ordre d’affichage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'type de place',
                'verbose_name_plural': 'types de place',
                'ordering': ['sort_order', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReservationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reservations.reservation', verbose_name='réservation')),
                ('ticket_type', models.ForeignKey(error_messages={'invalid': 'Choisissez un type de place existant.'}, on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='reservations.tickettype', verbose_name='type de place')),
            ],
            options={
                'verbose_name': 'ligne de réservation',
                'verbose_name_plural': 'lignes de réservation',
                'ordering': ['ticket_type__sort_order', 'ticket_type__name', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('event'), name='ticket_type_unique_name', violation_error_message='Ce type de place existe déjà pour cet événement.'),
        ),
        migrations.AddConstraint(
            model_name='reservationline',
            constraint=models.UniqueConstraint(fields=('reservation', 'ticket_type'), name='reservation_line_unique_type', violation_error_message='Ce type de place figure déjà dans la réservation.'),
        ),
        migrations.AddConstraint(
            model_name='reservationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='reservation_line_some_places', violation_error_message='Indiquez au moins une place.'),
        ),
    ]
