# Generated by Django 6.1.2 on 2026-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, db_default='', default='', help_text="Affichée dans l'espace bureau. Elle ne donne aucun droit.", max_length=100, verbose_name='fonction'),
        ),
    ]
