# Generated by Django 6.1.2 on 2026-10-09 05:21

from django.db import migrations

# Written out rather than imported from accounts/services/roles.py: a migration
# stays as it was when it ran, even if the code changes later.
BOARD_GROUP = 'Bureau'


def create_board_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=BOARD_GROUP)


def delete_board_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=BOARD_GROUP).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_position'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_board_group, reverse_code=delete_board_group),
    ]
