# Generated by Django 6.1.2 on 2026-10-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_board_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='lien envoyé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un compte existe déjà avec cette adresse.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('president', 'Président·e'), ('vice_president', 'Vice-président·e'), ('treasurer', 'Trésorier·e'), ('assistant_treasurer', 'Trésorier·e adjoint·e'), ('secretary', 'Secrétaire'), ('assistant_secretary', 'Secrétaire adjoint·e')], db_default='', default='', help_text="Affichée dans l'espace bureau. Elle ne donne aucun droit.", max_length=100, verbose_name='fonction'),
        ),
    ]
