# Generated by Django 6.1.2 on 2026-10-10 17:08

from django.db import migrations

# Written out rather than imported from accounts/models.py: a migration stays
# as it was when it ran, even if the code changes later.
POSITIONS = [
    'president',
    'vice_president',
    'treasurer',
    'assistant_treasurer',
    'secretary',
    'assistant_secretary',
]


def clear_unknown_positions(apps, schema_editor):
    """Empty a position typed before the list was closed (decision of
    10/10/2026): only a preproduction can hold one.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.exclude(position__in=['', *POSITIONS]).update(position='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_position_choices_and_link_sent_at'),
    ]

    operations = [
        # A position emptied cannot be told again: undone, the migration
        # leaves the accounts as they are.
        migrations.RunPython(clear_unknown_positions, reverse_code=migrations.RunPython.noop),
    ]
