# Generated by Django 6.1.2 on 2026-10-10 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='texte')),
                ('tag', models.CharField(blank=True, choices=[('minutes', 'Compte rendu'), ('budget', 'Budget'), ('logistics', 'Logistique')], max_length=20, null=True, verbose_name='étiquette')),
                ('pinned', models.BooleanField(default=False, verbose_name='épinglée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='écrite le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('event', models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un événement existant.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='events.event', verbose_name='événement')),
                ('parent', models.ForeignKey(blank=True, error_messages={'invalid': 'On ne répond qu’à une note, pas à une réponse.'}, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.note', verbose_name='note')),
            ],
            options={
                'verbose_name': 'note du bureau',
                'verbose_name_plural': 'notes du bureau',
                'constraints': [models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('event__isnull', True), ('pinned', False), ('tag__isnull', True)), _connector='OR'), name='note_reply_without_event_tag_or_pin', violation_error_message='Une réponse n’a ni événement, ni étiquette, ni épingle.')],
            },
        ),
    ]
