# Generated by Django 6.1.2 on 2026-10-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_document'),
        ('events', '0002_event_capacity'),
        ('notes', '0001_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un document existant.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='documents.document', verbose_name='pièce jointe'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), ('document__isnull', True), _connector='OR'), name='note_reply_without_document', violation_error_message='Une réponse n’a pas de pièce jointe.'),
        ),
    ]
