# Generated by Django 6.1.2 on 2026-10-10 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('required_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='personnes requises')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='ordre d’affichage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'poste',
                'ordering': ['sort_order', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='rôle')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stations.station', verbose_name='poste')),
            ],
            options={
                'verbose_name': 'affectation',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.CheckConstraint(condition=models.Q(('required_count__gte', 1)), name='station_requires_someone', violation_error_message='Il faut au moins une personne à un poste.'),
        ),
    ]
