# Generated by Django 6.1.2 on 2026-10-10 13:31

import django.core.validators
import django.db.models.deletion
import documents.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.document_path, verbose_name='fichier')),
                ('original_name', models.CharField(max_length=255, verbose_name='nom d’origine')),
                ('mime_type', models.CharField(max_length=50, verbose_name='type')),
                ('size', models.PositiveBigIntegerField(verbose_name='taille')),
                ('sha256', models.CharField(max_length=64, verbose_name='empreinte')),
                ('category', models.CharField(choices=[('invoice', 'Facture'), ('order', 'Commande'), ('minutes', 'Compte rendu'), ('misc', 'Divers')], max_length=20, verbose_name='catégorie')),
                ('status', models.CharField(choices=[('to_review', 'À vérifier'), ('validated', 'Validé')], default='to_review', max_length=20, verbose_name='statut')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='date du document')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='émetteur')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='numéro')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='montant')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='payée le')),
                ('extracted', models.JSONField(blank=True, default=dict, verbose_name='données extraites')),
                ('note', models.TextField(blank=True, verbose_name='remarque')),
                ('source', models.CharField(choices=[('upload', 'Dépôt'), ('v1_import', 'Import de la v1')], default='upload', max_length=20, verbose_name='source')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('event', models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un événement existant.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='events.event', verbose_name='événement')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'document',
                'constraints': [models.UniqueConstraint(fields=('sha256',), name='document_unique_sha256', violation_error_code='unique', violation_error_message='Ce fichier a déjà été déposé.'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'to_review'), ('validated_at__isnull', True)), models.Q(('status', 'validated'), ('validated_at__isnull', False)), _connector='OR'), name='document_validated_when_dated', violation_error_message='Un document validé porte la date de sa validation.')],
            },
        ),
    ]
