# Generated by Django 6.1.2 on 2026-10-10 14:20

from django.db import migrations

# Written out rather than imported from documents/services/notifications.py: a
# migration stays as it was when it ran, even if the code changes later.
DOCUMENT_NOTIFICATION_GROUP = 'Notifications documents'


def create_document_notification_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=DOCUMENT_NOTIFICATION_GROUP)


def delete_document_notification_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=DOCUMENT_NOTIFICATION_GROUP).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_document'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(
            create_document_notification_group, reverse_code=delete_document_notification_group
        ),
    ]
