# Generated by Django 6.1.2 on 2026-10-10 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='faite le')),
                ('assignee', models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un membre du bureau.'}, limit_choices_to=models.Q(('is_active', True), models.Q(('is_superuser', True), ('groups__name', 'Bureau'), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assignée à')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('event', models.ForeignKey(blank=True, error_messages={'invalid': 'Choisissez un événement existant.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'tâche',
            },
        ),
    ]
